services:

  solawi-bid_frontend:
    image: httpd:2-alpine
    ports:
      - "80:80"
    volumes:
      - ./solawi-bid-frontend/build/dist/js/productionExecutable/:/usr/local/apache2/htdocs/

  solawi-bid_database:
    image: mysql:9
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_DATABASE=solawi-bid
      - MYSQL_USER=solawi-bid
      - MYSQL_PASSWORD=secure
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s