services:

  solawi-bid_frontend:
    image: ghcr.io/joystick01/solawi-bid/frontend:latest
    ports:
      - "8080:80"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"
      interval: 2s
      timeout: 3s
      retries: 3
      start_period: 2m

  solawi-bid_backend:
    image: ghcr.io/joystick01/solawi-bid/backend:latest
    ports:
      - "8081:8080"
    environment:
      - KTOR_ENV=dev
      - BACKEND_PORT=8080
      - JWT_DOMAIN=solawi-bid_backend
      - JWT_AUDIENCE=solawi-bid_backend
      - JWT_REALM=solawi-bid_backend
      - JWT_SECRET=super-test-secret-for-solawi-bid
      - DATABASE_URL=jdbc:mysql://solawi-bid_database:3306/solawi-bid
      - DATABASE_DRIVER=com.mysql.jdbc.Driver
      - DATABASE_USER=solawi-bid
      - DATABASE_PASSWORD=secure
      - APPLICATION_OWNER_USERNAME=schmidt@alpha-structure.com
      - APPLICATION_OWNER_PASSWORD=\$2a\$10\$5EENEnXKE4oNT0AejWzy8Oa09DkBDiQTnk2LyqtqpBa3DrZijo51O
    container_name: solawi-bid_backend
    depends_on:
      solawi-bid_database:
        condition: service_healthy
    healthcheck:
      test: "curl 'http://localhost:8080/login' -f -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: http://localhost'"
      interval: 2s
      timeout: 3s
      retries: 3
      start_period: 2m

  solawi-bid_database:
    image: mysql:9
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_DATABASE=solawi-bid
      - MYSQL_USER=solawi-bid
      - MYSQL_PASSWORD=secure
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 2s
      timeout: 3s
      retries: 3
      start_period: 2m