services:

  solawi-bid_frontend:
    pull_policy: build
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile-Frontend
    ports:
      - "80:80"

  solawi-bid_backend:
    pull_policy: build
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile-Backend
    ports:
      - "8080:8080"
    environment:
      - KTOR_ENV=dev
      - BACKEND_PORT=8080
      - JWT_DOMAIN=solawi-bid_backend
      - JWT_AUDIENCE=solawi-bid_backend
      - JWT_REALM=solawi-bid_backend
      - JWT_SECRET=super-test-secret-for-solawi-bid
      - DATABASE_URL=jdbc:mysql://solawi-bid_database:3306/solawi-bid
      - DATABASE_DRIVER=com.mysql.jdbc.Driver
      - DATABASE_USER=solawi-bid
      - DATABASE_PASSWORD=secure
      - APPLICATION_OWNER_USERNAME=schmidt@alpha-structure.com
      - APPLICATION_OWNER_PASSWORD=\$2a\$10\$5EENEnXKE4oNT0AejWzy8Oa09DkBDiQTnk2LyqtqpBa3DrZijo51O
    container_name: solawi-bid_backend
    depends_on:
      solawi-bid_database:
        condition: service_healthy

  db:
    image: mysql:9
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_DATABASE=solawi-bid
      - MYSQL_USER=solawi-bid
      - MYSQL_PASSWORD=secure
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 20

  adminer:
    image: adminer
    hostname: adminer
    #container_name: adminer
    restart: always
    ports:
     - "8081:8080"
