package org.solyton.solawi.bid.module.application.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database

/**
 * Autogenerated [List] of [Migration]s. Alter with care!
 */
val applicationMigrations: ArrayList<Database.()-> Migration> by lazy{
    arrayListOf<Database.()-> Migration>(
        { Migration1756312925919(this) }
    )
}
