ktor {
    environment = dev
    environment = ${?KTOR_ENV}

    deployment {
        port = 8081
    }
    config{
        path = "/app/config/"
        modules = [
            "api"
        ]
    }
    application {
        modules = [
            org.solyton.solawi.bid.application.ApplicationKt.solawiBid
        ]
    }
}

jwt {
    domain = ${?JWT_DOMAIN}
    audience = ${?JWT_AUDIENCE}
    realm = ${?JWT_REALM}
    secret = ${?JWT_SECRET}
}

database {
    url = ${?DATABASE_URL}
    driver = ${?DATABASE_DRIVER}
    user = ${?DATABASE_USER}
    password = ${?DATABASE_PASSWORD}
}

users {
    owner {
        username = ${?APPLICATION_OWNER_USERNAME}
        password = ${?APPLICATION_OWNER_PASSWORD}
    }
}

mail {
    smtp {
        host = ${?SMTP_HOST}
        port = ${?SMTP_PORT}
        auth = ${?SMTP_AUTH}
        user = ${?SMTP_USER}
        password = ${?SMTP_PASSWORD}
        startTslEnabled = ${?SMTP_STARTTLS_ENABLE}
    }
    defaultResponseAddress = ${?DEFAULT_RESPONSE_ADDRESS}
}
