// This file has been partially auto generated. 
// Please don't make any changes to the lenses.
// Feel free to add or remove annotated properties from
// the generator data class. The corresponding lenses 
// will be removed or added on the next run of the 
// lens generator. See below for more details.
package org.solyton.solawi.bid.module.application.data.organizationapplication

import org.evoleq.optics.Lensify
import org.evoleq.optics.ReadWrite
import org.evoleq.optics.lens.Lens
import org.solyton.solawi.bid.module.application.data.application.Application

/**
 * Generator class.
 * Feel free to add or remove annotated properties from
 * the class. Make sure that they are annotated with
 * - @ReadOnly
 * - @ReadWrite
 * If you want that a property-lens will be generated
 * on the next run of the lens generator.
 * If not, just omit the annotation or annotate it with @Ignore.
 */
@Lensify data class OrganizationApplications(
    @ReadWrite val organizationId: String,
    @ReadWrite val applications: List<Application>
)

/**
 * Autogenerated Lens.
 * Read and manipulate [OrganizationApplications.organizationId]
 */
@ReadWrite val organizationId: Lens<OrganizationApplications, String> by lazy{ Lens(
    get = {whole -> whole.organizationId},
    set = {part -> {whole -> whole.copy(organizationId = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [OrganizationApplications.organizationId]
 */
@ReadWrite fun OrganizationApplications.organizationId(set: String.()->String ): OrganizationApplications = copy(organizationId = set(organizationId)) 
/**
 * Autogenerated Lens.
 * Read and manipulate [OrganizationApplications.applications]
 */
@ReadWrite val applications: Lens<OrganizationApplications, List<Application>> by lazy{ Lens(
    get = {whole -> whole.applications},
    set = {part -> {whole -> whole.copy(applications = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [OrganizationApplications.applications]
 */
@ReadWrite fun OrganizationApplications.applications(set: List<Application>.()->List<Application> ): OrganizationApplications = copy(applications = set(applications)) 
