fr {
    solyton {
        countries {
            stateOrProvince {
                CH {
                    CH-AG: "Argovie"
                    CH-AR: "Appenzell Rhodes-Extérieures"
                    CH-AI: "Appenzell Rhodes-Intérieures"
                    CH-BL: "Bâle-Campagne"
                    CH-BS: "Bâle-Ville"
                    CH-BE: "Berne"
                    CH-FR: "Fribourg"
                    CH-GE: "Genève"
                    CH-GL: "Glaris"
                    CH-GR: "Grisons"
                    CH-JU: "Jura"
                    CH-LU: "Lucerne"
                    CH-NE: "Neuchâtel"
                    CH-NW: "Nidwald"
                    CH-OW: "Obwald"
                    CH-SG: "Saint-Gall"
                    CH-SH: "Schaffhouse"
                    CH-SZ: "Schwytz"
                    CH-SO: "Soleure"
                    CH-TG: "Thurgovie"
                    CH-TI: "Tessin"
                    CH-UR: "Uri"
                    CH-VS: "Valais"
                    CH-VD: "Vaud"
                    CH-ZG: "Zoug"
                    CH-ZH: "Zurich"
                }
            }
        }
    }
}
