// This file has been partially auto generated. 
// Please don't make any changes to the lenses.
// Feel free to add or remove annotated properties from
// the generator data class. The corresponding lenses 
// will be removed or added on the next run of the 
// lens generator. See below for more details.
package org.solyton.solawi.bid.module.application.data.organizationrelation

import org.evoleq.optics.Lensify
import org.evoleq.optics.ReadWrite
import org.evoleq.optics.lens.Lens

/**
 * Generator class.
 * Feel free to add or remove annotated properties from
 * the class. Make sure that they are annotated with
 * - @ReadOnly
 * - @ReadWrite
 * If you want that a property-lens will be generated
 * on the next run of the lens generator.
 * If not, just omit the annotation or annotate it with @Ignore.
 */
@Lensify data class ApplicationOrganizationRelation(
    @ReadWrite val applicationId: String,
    @ReadWrite val organizationId: String,
    @ReadWrite val moduleIds: List<String> = listOf()
)

/**
 * Autogenerated Lens.
 * Read and manipulate [ApplicationOrganizationRelation.applicationId]
 */
@ReadWrite val applicationId: Lens<ApplicationOrganizationRelation, String> by lazy{ Lens(
    get = {whole -> whole.applicationId},
    set = {part -> {whole -> whole.copy(applicationId = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [ApplicationOrganizationRelation.applicationId]
 */
@ReadWrite fun ApplicationOrganizationRelation.applicationId(set: String.()->String ): ApplicationOrganizationRelation = copy(applicationId = set(applicationId)) 
/**
 * Autogenerated Lens.
 * Read and manipulate [ApplicationOrganizationRelation.organizationId]
 */
@ReadWrite val organizationId: Lens<ApplicationOrganizationRelation, String> by lazy{ Lens(
    get = {whole -> whole.organizationId},
    set = {part -> {whole -> whole.copy(organizationId = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [ApplicationOrganizationRelation.organizationId]
 */
@ReadWrite fun ApplicationOrganizationRelation.organizationId(set: String.()->String ): ApplicationOrganizationRelation = copy(organizationId = set(organizationId)) 
/**
 * Autogenerated Lens.
 * Read and manipulate [ApplicationOrganizationRelation.moduleIds]
 */
@ReadWrite val moduleIds: Lens<ApplicationOrganizationRelation, List<String>> by lazy{ Lens(
    get = {whole -> whole.moduleIds},
    set = {part -> {whole -> whole.copy(moduleIds = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [ApplicationOrganizationRelation.moduleIds]
 */
@ReadWrite fun ApplicationOrganizationRelation.moduleIds(set: List<String>.()->List<String> ): ApplicationOrganizationRelation = copy(moduleIds = set(moduleIds)) 
