FROM gradle:8-jdk17-noble AS build

WORKDIR /build
COPY . /build

RUN gradle solawi-bid-frontend:build -x jsBrowserTest

FROM httpd:2-alpine

ENV ENVIRONMENT="D"
ENV FRONTEND_URL="http://localhost"
ENV FRONTEND_PORT="80"
ENV BACKEND_URL="http://localhost"
ENV BACKEND_PORT="8080"

RUN apk add --no-cache envsubst
COPY --from=build /build/solawi-bid-frontend/build/dist/js/productionExecutable/ /usr/local/apache2/htdocs
CMD ["sh", "-c", "envsubst < /usr/local/apache2/htdocs/config.json.template > /usr/local/apache2/htdocs/config.json && httpd-foreground"]