FROM ghcr.io/doctor-smith/gradle-base-frontend:latest AS build

WORKDIR /build
COPY . /build

RUN --mount =type=cache,target=/home/gradle/.gradle gradle solawi-bid-frontend:build -x jsBrowserTest
RUN --mount=type=cache,target=/home/gradle/.gradle \
      gradle --continue \
        solawi-bid-frontend:jsTest \
        solawi-bid-api-data:jsTest \
        evoleq:jsTest

RUN cp -r /build/solawi-bid-frontend/build/test-results/. /test-results/
RUN cp -r /build/solawi-bid-api-data/build/test-results/. /test-results/
RUN cp -r /build/evoleq/build/test-results/. /test-results/

FROM nginx:1-alpine as production

ENV ENVIRONMENT="D"
ENV FRONTEND_URL="http://localhost"
ENV FRONTEND_PORT="8080"
ENV BACKEND_URL="http://localhost"
ENV BACKEND_PORT="8081"

COPY infrastructure/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /build/solawi-bid-frontend/build/dist/js/productionExecutable/ /usr/share/nginx/html
CMD ["sh", "-c", "envsubst < /usr/share/nginx/html/config.json.template > /usr/share/nginx/html/config.json && nginx -g 'daemon off;'"]