FROM gradle:8-jdk17-noble AS build

WORKDIR /build
COPY . /build

RUN --mount=type=cache,target=/home/gradle/.gradle \
    gradle --continue \
      solawi-bid-backend:test \
      solawi-bid-backend:unitTest \
      solawi-bid-backend:schemaTest \
      solawi-bid-backend:dbFunctionalTest \
      solawi-bid-backend:apiTest

RUN --mount=type=cache,target=/home/gradle/.gradle gradle solawi-bid-backend:buildFatJar

RUN mkdir -p /test-results && \
    mkdir -p /build/solawi-bid-backend/build/test-results && \
    cp -r /build/solawi-bid-backend/build/test-results/. /test-results/


FROM eclipse-temurin:17 as production

WORKDIR /app
COPY --from=build /build/solawi-bid-backend/build/resources/main/application.env.conf /app/application.conf
COPY --from=build /build/solawi-bid-backend/build/libs/*-all.jar /app/server.jar

ENTRYPOINT ["java","-jar","/app/server.jar", "-config=/app/application.conf"]