package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.banking.schema.*

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Sun Mar 22 10:39:42 CET 2026
 *
 * Description: Generate Banking tables (needed for SEPA)
 * - LegalEntitiesTable,
 * - CreditorIdentifiersTable,
 * - SepaMandatesTable,
 * - SepaMessagesTable,
 * - CreditorBankAccessTable,
 * - DebtorBankAccessTable
 */
class Migration1774172382379(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1774172382379

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(
            LegalEntitiesTable,
            CreditorIdentifiersTable,
            SepaMandatesTable,
            SepaMessagesTable,
            CreditorBankAccessTable,
            DebtorBankAccessTable
        )
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
