package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.shares.schema.CoSubscribersTable

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Wed Jan 28 16:07:53 CET 2026
 *
 * Description: Add table [org.solyton.solawi.bid.module.shares.schema.CoSubscribers]
 */
class Migration1769612873583(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1769612873583

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(CoSubscribersTable)
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
