package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.evoleq.uuid.UUID_ZERO
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.application.repository.createApplication
import org.solyton.solawi.bid.module.application.repository.createModule
import org.solyton.solawi.bid.module.permission.repository.*

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Wed Mar 18 11:45:41 CET 2026
 *
 * Description: Create Rights related to ShareManagement
 */
class Migration1773830741687(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1773830741687

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val applicationContext = createRootContext("SHARE_MANAGEMENT")
        val application = createApplication(
            applicationName = "SHARE_MANAGEMENT",
            applicationDescription = "Share management application. Allows to manage shares, share types, share offers, share subscriptions, import and export share subscriptions.",
            creator = UUID_ZERO,
            isMandatory = false,
            defaultContextId = applicationContext.id.value
        )
        val shareManagementContext = applicationContext.createChild("SHARE_MANAGEMENT")
        createModule(
            moduleName = "SHARE_MANAGEMENT",
            moduleDescription = "Manage shares",
            applicationId = application.id.value,
            creator = UUID_ZERO,
            isMandatory = true,
            defaultContextId = shareManagementContext.id.value
        )
        val manageShares = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "MANAGE_SHARES",
            description = "Manage shares"
        )
        val manageShareTypes = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "MANAGE_SHARE_TYPES",
            description = "Manage share types"
        )
        val createShareTypes = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "CREATE_SHARE_TYPES",
            description = "Create share types"
        )
        val readShareTypes = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "READ_SHARE_TYPES",
            description = "Read share types"
        )
        val updateShareTypes = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "UPDATE_SHARE_TYPES",
            description = "Update share types"
        )
        val deleteShareTypes = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "DELETE_SHARE_TYPES",
            description = "Delete share types"
        )
        val createShareOffers = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "CREATE_SHARE_OFFERS",
            description = "Create share offers"
        )
        val readShareOffers = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "READ_SHARE_OFFERS",
            description = "Read share offers"
        )
        val updateShareOffers = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "UPDATE_SHARE_OFFERS",
            description = "Update share offers"
        )
        val deleteShareOffers = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "DELETE_SHARE_OFFERS",
            description = "Delete share offers"
        )
        val manageShareOffers = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "MANAGE_SHARE_OFFERS",
            description = "Manage share offers"
        )
        val createShareSubscriptions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "CREATE_SHARE_SUBSCRIPTIONS",
            description = "Create a share subscription"
        )
        val readShareSubscriptions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "READ_SHARE_SUBSCRIPTIONS",
            description = "Read a share subscription"
        )
        val updateShareSubscriptions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "UPDATE_SHARE_SUBSCRIPTIONS",
            description = "Update a share subscription"
        )
        val deleteShareSubscriptions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "DELETE_SHARE_SUBSCRIPTIONS",
            description = "Delete a share subscription"
        )
        val manageShareSubscriptions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "MANAGE_SHARE_SUBSCRIPTIONS",
            description = "Manage a share subscription"
        )
        val importShareSubscriptions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "IMPORT_SHARE_SUBSCRIPTIONS",
            description = "Import a share subscription"
        )
        val exportShareSubscriptions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "EXPORT_SHARE_SUBSCRIPTIONS",
            description = "Export a share subscription"
        )

        val shareManager = createRoleIfNotExists(
            creator = UUID_ZERO,
            name = "SHARE_MANAGER",
            description = "Manage shares"
        )
        val shareHolder = createRoleIfNotExists(
            creator = UUID_ZERO,
            name = "SHARE_HOLDER",
            description = "Hold shares"
        )

        (shareManager of applicationContext).grant(
            manageShares,
            manageShareTypes,
            createShareTypes,
            readShareTypes,
            updateShareTypes,
            deleteShareTypes,
            createShareOffers,
            readShareOffers,
            updateShareOffers,
            deleteShareOffers,
            manageShareOffers,
            createShareSubscriptions,
            readShareSubscriptions,
            updateShareSubscriptions,
            deleteShareSubscriptions,
            manageShareSubscriptions,
            importShareSubscriptions,
            exportShareSubscriptions
        )

        (shareHolder of applicationContext).grant(
            createShareSubscriptions,
            readShareSubscriptions,
            updateShareSubscriptions,
            deleteShareSubscriptions,
        )

        val assignRoles = readRightByName("ASSIGN_ROLES")
        val managePermissions = readRightByName("MANAGE_PERMISSIONS")
        val permissionManager = readRoleByName("PERMISSION_MANAGER")
        (permissionManager of applicationContext).grant(
            assignRoles,
            managePermissions
        )

        val owner = readRoleByName("OWNER")
        (owner of applicationContext).grant(
            manageShares,
            manageShareTypes,
            createShareTypes,
            readShareTypes,
            updateShareTypes,
            deleteShareTypes,
            createShareOffers,
            readShareOffers,
            updateShareOffers,
            assignRoles,
            managePermissions,
        )
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
