package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.bid.schema.ShareOffers
import org.solyton.solawi.bid.module.bid.schema.ShareStatusTable
import org.solyton.solawi.bid.module.bid.schema.ShareSubscriptions
import org.solyton.solawi.bid.module.bid.schema.ShareTypes

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Sun Jan 18 06:57:53 CET 2026
 *
 * Description: Refactor tables related to shares
 */
class Migration1768715873148(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1768715873148

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val dropSharesStatement = "DROP TABLE IF EXISTS shares"

        exec(dropSharesStatement)

        SchemaUtils.create(
            ShareTypes,
            ShareStatusTable,
            ShareOffers,
            ShareSubscriptions,
        )
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
