package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.application.schema.ApplicationEntity
import org.solyton.solawi.bid.module.application.schema.ApplicationsTable
import org.solyton.solawi.bid.module.application.schema.ModuleEntity
import org.solyton.solawi.bid.module.application.schema.ModulesTable

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Fri Sep 12 11:08:46 CEST 2025
 *
 * Description:
 * Set mandatory m modules for AUCTIONS application
 */
class Migration1757668126066(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1757668126066

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {

        val mandatoryAuctionModules = setOf(
            "AUCTION_MANAGEMENT",
            "ORGANIZATION_MANAGEMENT"
        )

        val auctionApplication = ApplicationEntity.find {
            ApplicationsTable.name eq "AUCTIONS"
        }.first()

        val modules = auctionApplication.modules.toList().filter {
            module -> module.name in mandatoryAuctionModules
        }

        modules.forEach {
            module -> module.isMandatory = true
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
