package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database

/**
 * Autogenerated [List] of [Migration]s. Alter with care!
 */
val applicationMigrations: ArrayList<Database.()-> Migration> by lazy{
    arrayListOf<Database.()-> Migration>(
        { Migration1712001749830(this) },
        { Migration1730143239225(this) },
        { Migration1730143239229(this) },
        { Migration1731853772782(this) },
        { Migration1731854081411(this) },
        { Migration1734877651652(this) },
        { Migration1735334305003(this) },
        { Migration1741090756524(this) },
        { Migration1742401223055(this) },
        { Migration1743235367945(this) },
        { Migration1743786680319(this) },
        { Migration1755549920680(this) },
        { Migration1755634655117(this) },
        { Migration1755636467155(this) },
        { Migration1755717483732(this) },
        { Migration1755719399966(this) },
        { Migration1755940945991(this) },
        { Migration1756194509999(this) },
        { Migration1757668126066(this) },
        { Migration1758956119471(this) },
        { Migration1759040092787(this) },
        { Migration1760257040030(this) },
        { Migration1760694080848(this) },
        { Migration1761575845606(this) },
        { Migration1761577961366(this) },
        { Migration1763214147468(this) },
        { Migration1767085791665(this) },
        { Migration1767086063932(this) },
        { Migration1768715873148(this) },
        { Migration1769413529413(this) },
        { Migration1769430572290(this) },
        { Migration1769430754066(this) },
        { Migration1769612873583(this) },
        { Migration1770227363170(this) },
        { Migration1771011411603(this) },
        { Migration1772786507921(this) },
        { Migration1773830741687(this) },
        { Migration1773831198061(this) },
        { Migration1773831431137(this) },
        { Migration1774172382379(this) }
    )
}
