package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Mon Jan 26 13:29:32 CET 2026
 *
 * Description: Add table [org.solyton.solawi.bid.module.system.schema.SystemProcess]
 */
class Migration1769430572290(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1769430572290

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        TODO("Not yet implemented")
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
