package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.shares.schema.ShareStatusEntity

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Wed Feb 04 18:49:23 CET 2026
 *
 * Description: Add [org.solyton.solawi.bid.module.shares.data.internal.ShareStatus]es
 * to initialize the system with predefined share statuses including EXTERNAL, SUBSCRIBED,
 * PAUSED, SUSPENDED, PENDING_ACTIVATION, CLEARED_FOR_AUCTION, ACTIVATION_REJECTED,
 * AWAITING_AHC_AUTHORIZATION, PAYMENT_FAILED, CANCELLED, EXPIRED, ROLLED_OVER, and ROLLING_OVER
 * 
 */
class Migration1770227363170(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1770227363170

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        ShareStatusEntity.new {
            name = "EXTERNAL"
            description = "Share is not managed by the system"
        }
        ShareStatusEntity.new {
            name = "SUBSCRIBED"
            description = "Share is subscribed to by the user"
        }
        ShareStatusEntity.new {
            name = "PAUSED"
            description = "Share is paused by the user"
        }
        ShareStatusEntity.new {
            name = "SUSPENDED"
            description = "Share is suspended by provider or system"
        }
        ShareStatusEntity.new {
            name = "PENDING_ACTIVATION"
            description = "Share is pending activation by the user"
        }
        ShareStatusEntity.new {
            name = "CLEARED_FOR_AUCTION"
            description = "Share is cleared for auction"
        }
        ShareStatusEntity.new {
            name = "ACTIVATION_REJECTED"
            description = "Share activation was rejected by the provider"
        }
        ShareStatusEntity.new {
            name = "AWAITING_AHC_AUTHORIZATION"
            description = "Share is awaiting authorization from the AHC"
        }
        ShareStatusEntity.new {
            name = "PAYMENT_FAILED"
            description = "Payment failed"
        }
        ShareStatusEntity.new {
            name = "CANCELLED"
            description = "Share was cancelled by the user, the provider or the system"
        }
        ShareStatusEntity.new {
            name = "EXPIRED"
            description = "Share expired"
        }
        ShareStatusEntity.new {
            name = "ROLLED_OVER"
            description = "Share was rolled over"
        }
        ShareStatusEntity.new {
            name = "ROLLING_OVER"
            description = "Share is rolling over"
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
