package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.shares.processes.ShareManagementProcesses
import org.solyton.solawi.bid.module.system.schema.SystemProcess
import org.solyton.solawi.bid.module.application.processes.Processes.Application as ApplicationProcesses
import org.solyton.solawi.bid.module.user.processes.Processes.Users as UsersProcesses

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Mon Jan 26 13:32:34 CET 2026
 *
 * Description: Add basic [SystemProcess]es
 */
class Migration1769430754066(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1769430754066

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SystemProcess.new{
            name = UsersProcesses.USER_MANAGEMENT
            description = "Processes related automatic changes of user data"
        }

        SystemProcess.new{
            name = ShareManagementProcesses.SHARE_MANAGEMENT
            description = "Processes related automatic changes of shares within the Auctions application"
        }

        SystemProcess.new{
            name = ApplicationProcesses.LIFECYCLE_MANAGEMENT
            description = "Processes related automatic changes of lifecycle stages in application management"
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
