package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.banking.schema.SepaMandateDataMappings

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Sun Apr 12 16:46:18 CEST 2026
 *
 * Description: Add table SepaMandateDataMappings
 */
class Migration1776005178767(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1776005178767

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(SepaMandateDataMappings)
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
