package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.banking.schema.SepaMandateCollectionEntity
import org.solyton.solawi.bid.module.banking.schema.SepaMandateCollectionsTable
import org.solyton.solawi.bid.module.banking.schema.SepaMandateEntity
import org.solyton.solawi.bid.module.banking.schema.SepaMandatesTable

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Wed Jun 17 18:52:56 CEST 2026
 *
 * Description:
 * Migrate all existing relations between sepa mandates and collections to the mapping table
 */
class Migration1781715176835(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1781715176835

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(SepaMandateCollectionsTable)

        val mandates = SepaMandateEntity.find { SepaMandatesTable.collectionId.isNotNull() }.toList()
        mandates.filter{ mandate ->
            mandate.collections.count() == 0L
        }.forEach { mandate ->
            SepaMandateCollectionEntity.new {
                val collection = requireNotNull(mandate.collection)
                this.sepaMandate = mandate
                this.sepaCollection = collection
            }
            mandate.collection = null
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
