package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.application.schema.Applications
import org.solyton.solawi.bid.module.application.schema.Modules
import org.solyton.solawi.bid.module.application.schema.UserApplications
import org.solyton.solawi.bid.module.application.schema.UserModules

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Mon Aug 18 22:45:20 CEST 2025
 *
 * Description:
 * Add tables
 * - Applications,
 * - Modules,
 * - UserApplications,
 * - UserModules
 */
class Migration1755549920680(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1755549920680

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(
            Applications,
            Modules,
            UserApplications,
            UserModules
        )
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
