package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.banking.schema.SepaCollectionMappings
import org.solyton.solawi.bid.module.banking.schema.SepaCollections
import org.solyton.solawi.bid.module.banking.schema.SepaCollectionsTable
import org.solyton.solawi.bid.module.banking.schema.SepaPaymentStatusHistory
import org.solyton.solawi.bid.module.banking.schema.SepaPayments
import org.solyton.solawi.bid.module.banking.schema.SepaPaymentsTable

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Mon Apr 06 09:46:51 CEST 2026
 *
 * Description: Add tables
 * - SepaCollectionsTable,
 * - SepaPaymentsTable,
 * - SepaPaymentStatusHistory
 * - SepaCollectionMappings
 */
class Migration1775461611681(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1775461611681

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(
            SepaCollectionsTable,
            SepaPaymentsTable,
            SepaPaymentStatusHistory,
            SepaCollectionMappings
        )
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
