package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.permission.schema.RightEntity
import org.solyton.solawi.bid.module.permission.schema.RightsTable

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Fri Aug 28 09:47:40 CEST 2026
 *
 * Description: Repair names of rights. E.g. "Export Results" -> "EXPORT_RESULTS"
 */
class Migration1787903260875(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1787903260875

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val right = RightEntity.find { RightsTable.name eq "Export Results" }.firstOrNull()
        right?.let { it.name = "EXPORT_RESULTS" }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
