package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.JoinType
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.Transaction
import org.jetbrains.exposed.sql.alias
import org.jetbrains.exposed.sql.insert
import org.jetbrains.exposed.sql.selectAll
import org.jetbrains.exposed.sql.update
import org.solyton.solawi.bid.module.banking.schema.SepaPaymentEntity
import org.solyton.solawi.bid.module.banking.schema.SepaPaymentLinksTable
import org.solyton.solawi.bid.module.banking.schema.SepaPaymentsTable
import org.solyton.solawi.bid.module.banking.schema.SuccessorKind

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Sat Jun 27 16:45:00 CEST 2026
 *
 * Description:
 * 1. Create SepaPaymentLinks table
 * 2. Create SepaPaymentLinks for all payments with a successorId
 */
class Migration1782571500277(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1782571500277

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(SepaPaymentLinksTable)

        // Now each successor of a SepaPayment needs to be transformed to a SepaPaymentLink
        // Plan:
        // Iterate over all payments, find all payments with a successorId, and create a SepaPaymentLink for each of them
        // and then set the successorId of the payment to null
        //
        // Hints / Facts:
        // 1. Until now, we have only one successor per payment, and
        // 2. its type is SuccessorKind.NEXT_PERIOD,
        // so we can use the first one!
        //
        // Step 1: Create SepaPaymentLinks
        val predecessorTable = SepaPaymentsTable.alias("predecessor")
        val successorTable = SepaPaymentsTable.alias("successor")
        
        predecessorTable
            .join(
                successorTable, 
                JoinType.INNER,
                predecessorTable[SepaPaymentsTable.successorId],
                successorTable[SepaPaymentsTable.id]
            )
            .selectAll()
            .where { predecessorTable[SepaPaymentsTable.successorId].isNotNull() }
            .forEach { row ->
                SepaPaymentLinksTable.insert {
                    it[SepaPaymentLinksTable.predecessorId] = row[predecessorTable[SepaPaymentsTable.id]].value
                    it[SepaPaymentLinksTable.successorId] = row[successorTable[SepaPaymentsTable.id]].value
                    it[SepaPaymentLinksTable.kind] = SuccessorKind.NEXT_PERIOD
                    it[SepaPaymentLinksTable.createdAt] = row[successorTable[SepaPaymentsTable.createdAt]]
                    it[SepaPaymentLinksTable.createdBy] = row[successorTable[SepaPaymentsTable.createdBy]]
                }
            }

        // Step 2: Set successorId to null
        SepaPaymentsTable.update({ SepaPaymentsTable.successorId.isNotNull() }) {
            it[SepaPaymentsTable.successorId] = null
        }
    }


    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
