package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.evoleq.uuid.UUID_ZERO
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.application.repository.createApplication
import org.solyton.solawi.bid.module.application.repository.createModule

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Tue Aug 19 22:47:47 CEST 2025
 *
 * Description:
 * - Add Application manage Applications
 */
class Migration1755636467155(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1755636467155

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val applicationManagementApplication = createApplication(
            "APPLICATION_MANAGEMENT",
            "Manage all aspects of the Solyton Application",
            UUID_ZERO
        )

        createModule(
            "ORGANIZATION_MANAGEMENT",
            "Manage members, Access rights",
            applicationManagementApplication.id.value,
            UUID_ZERO
        )
        createModule(
            "TECHNICAL_APPLICATION_MANAGEMENT",
            "Manage applications, modules, Rights and Roles",
            applicationManagementApplication.id.value,
            UUID_ZERO
        )
        createModule(
            "APPLICATION_USER_MANAGEMENT",
            "Manage Access to Apps",
            applicationManagementApplication.id.value,
            UUID_ZERO
        )
        createModule(
            "FINANCIAL_TOOLING",
            "Financial Tooling, Reporting, Forecasts",
            applicationManagementApplication.id.value,
            UUID_ZERO
        )
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
