package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.evoleq.uuid.UUID_ZERO
import org.jetbrains.exposed.sql.*
import org.solyton.solawi.bid.module.permission.schema.*

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Mon Oct 28 20:20:39 CET 2024
 *
 * Description:
 * - Add role Permission Manager
 */
class Migration1730143239229(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1730143239229

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        RoleEntity.new {
            createdBy = UUID_ZERO
            name = "PERMISSION_MANAGER"
            description = "Permission Manager"
        }
        RightEntity.new {
            createdBy = UUID_ZERO
            name = "MANAGE_PERMISSIONS"
            description = "Assign permissions"
        }
        RightEntity.new {
            createdBy = UUID_ZERO
            name = "ASSIGN_ROLES"
            description = "Assign / unassign roles"
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
