package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.Transaction
import org.jetbrains.exposed.sql.and
import org.solyton.solawi.bid.module.application.repository.registerForApplication
import org.solyton.solawi.bid.module.application.repository.registerForModule
import org.solyton.solawi.bid.module.application.schema.ApplicationEntity
import org.solyton.solawi.bid.module.application.schema.ApplicationsTable
import org.solyton.solawi.bid.module.application.schema.LifecycleStageEntity
import org.solyton.solawi.bid.module.application.schema.LifecycleStagesTable
import org.solyton.solawi.bid.module.application.schema.ModuleEntity
import org.solyton.solawi.bid.module.application.schema.ModulesTable
import org.solyton.solawi.bid.module.application.schema.UserApplicationEntity
import org.solyton.solawi.bid.module.application.schema.UserApplicationsTable
import org.solyton.solawi.bid.module.application.schema.UserModuleEntity
import org.solyton.solawi.bid.module.application.schema.UserModulesTable
import org.solyton.solawi.bid.module.user.schema.UserEntity
import org.solyton.solawi.bid.module.user.schema.UsersTable

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Tue Dec 30 10:14:23 CET 2025
 *
 * Description: Register owner for APPLICATION_MANAGEMENT application
 */
class Migration1767086063932(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1767086063932

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val user = UserEntity.find { UsersTable.username eq "owner@solyton.org" }.first()
        val application = ApplicationEntity.find { ApplicationsTable.name eq "APPLICATION_MANAGEMENT" }.first()
        val active = LifecycleStageEntity.find { LifecycleStagesTable.name eq "ACTIVE" }.first()
        val notRegistered = UserApplicationEntity.find {
            (UserApplicationsTable.applicationId eq application.id) and
                    (UserApplicationsTable.userId eq user.id.value)
        }.empty()
        if(notRegistered) {
            val registeredApplication = registerForApplication(user.id.value, application.id.value)
            registeredApplication.lifecycleStage = active
        }
        val modules = ModuleEntity.find {
            ModulesTable.applicationId eq application.id
        }.toList()
        modules.forEach { module ->
            val notRegisteredModule = UserModuleEntity.find {
                (UserModulesTable.moduleId eq module.id) and
                (UserModulesTable.userId eq user.id.value)
            }.empty()
            if(notRegisteredModule) {
                val registeredModule = registerForModule(user.id.value, module.id.value)
                registeredModule.lifecycleStage = active
            }
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
