package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.evoleq.uuid.UUID_ZERO
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.application.repository.createApplication
import org.solyton.solawi.bid.module.application.repository.createModule
import org.solyton.solawi.bid.module.permission.repository.*

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Wed Mar 18 11:53:18 CET 2026
 *
 * Description:
 * - Create rights related to DistributionPoint Management
 * - Create basic roles related to DistributionPoint Management
 * - Create Distribution Application
 * - Create default application context
 */
class Migration1773831198061(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1773831198061

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val applicationContext = createRootContext("DISTRIBUTION")
        val application = createApplication(
            applicationName = "DISTRIBUTION",
            applicationDescription = "Application for managing distribution points",
            creator = UUID_ZERO,
            isMandatory = false,
            defaultContextId = applicationContext.id.value
        )
        val depotManagementContext = applicationContext.createChild("DISTRIBUTION_POINT_MANAGEMENT")
        // val depotManagementModule =
        createModule(
            moduleName = "DISTRIBUTION_POINT_MANAGEMENT",
            moduleDescription = "Manage Distribution Points",
            applicationId = application.id.value,
            creator = UUID_ZERO,
            isMandatory = true,
            defaultContextId = depotManagementContext.id.value
        )
        val depotPlannerContext = applicationContext.createChild("DISTRIBUTION_POINT_PLANNER")
        // val depotPlannerModule =
        createModule(
            moduleName = "DISTRIBUTION_POINT_PLANNER",
            moduleDescription = "Plan Distribution Points",
            applicationId = application.id.value,
            creator = UUID_ZERO,
            isMandatory = false,
            defaultContextId = depotPlannerContext.id.value
        )
        val distributionPointManager = createRoleIfNotExists(
            creator = UUID_ZERO,
            name = "DISTRIBUTION_POINT_MANAGER",
            description = "Manage distribution points"
        )
        

        val user = readRoleByName("USER")

        val manageDistributionPoints = createRightIfNotExists(
            name = "MANAGE_DISTRIBUTION_POINTS",
            description = "Allows to manage distribution points",
            creator = UUID_ZERO,
        )
        val createDistributionPoints = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "CREATE_DISTRIBUTION_POINTS",
            description = "Allows to create a new distribution point"
        )
        val deleteDistributionPoints = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "DELETE_DISTRIBUTION_POINTS",
            description = "Allows to delete a distribution point"
        )
        val updateDistributionPoints = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "UPDATE_DISTRIBUTION_POINTS",
            description = "Allows to update a distribution point"
        )
        val readDistributionPoints = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "READ_DISTRIBUTION_POINTS",
            description = "Allows to read a distribution point"
        )

        // grant rights
        (distributionPointManager of applicationContext).grant (
            manageDistributionPoints,
            createDistributionPoints,
            deleteDistributionPoints,
            updateDistributionPoints,
            readDistributionPoints
        )

        (user of applicationContext).grant(
            readDistributionPoints
        )

        val assignRoles = readRightByName("ASSIGN_ROLES")
        val managePermissions = readRightByName("MANAGE_PERMISSIONS")
        val permissionManager = readRoleByName("PERMISSION_MANAGER")
        (permissionManager of applicationContext).grant(
            assignRoles,
            managePermissions
        )

        val owner = readRoleByName("OWNER")
        (owner of applicationContext).grant(
            manageDistributionPoints,
            assignRoles,
            managePermissions,
        )
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
