package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.JoinType
import org.jetbrains.exposed.sql.Transaction
import org.jetbrains.exposed.sql.insert
import org.jetbrains.exposed.sql.selectAll
import org.solyton.solawi.bid.module.application.permission.Context
import org.solyton.solawi.bid.module.permission.PermissionException
import org.solyton.solawi.bid.module.permission.exception.PermissionExceptionD
import org.solyton.solawi.bid.module.permission.schema.ContextEntity
import org.solyton.solawi.bid.module.permission.schema.ContextsTable
import org.solyton.solawi.bid.module.permission.schema.RoleEntity
import org.solyton.solawi.bid.module.permission.schema.RolesTable
import org.solyton.solawi.bid.module.permission.schema.UserRoleContext
import org.solyton.solawi.bid.module.user.schema.UserEntity
import org.solyton.solawi.bid.module.user.schema.UsersTable

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Fri Mar 06 09:41:47 CET 2026
 *
 * Description: Check permissions of each user. If the user does not belong to the APPLICATION context, then add him 
 * with the standard user role. 
 */
class Migration1772786507921(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1772786507921

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val applicationContext = ContextEntity.find { ContextsTable.name eq Context.Application.value }
            .firstOrNull()?: throw PermissionException.NoSuchContext(Context.Application.value)
        
        val userRole = RoleEntity.find { RolesTable.name eq "USER" }
            .firstOrNull()?: throw PermissionExceptionD.NoSuchRole("USER")
        
        val applicationUsers = (UserRoleContext.join(UsersTable,
            JoinType.INNER,
            UserRoleContext.userId,
            UsersTable.id)
        ).selectAll().where {
            UserRoleContext.contextId eq applicationContext.id
        }.map { it[UsersTable.id] }.toList()
        
        val usersToFix = UserEntity.find { UsersTable.id notInList applicationUsers }.toList()
        
        usersToFix.forEach { user ->
            UserRoleContext.insert { 
                it[userId] = user.id.value; 
                it[contextId] = applicationContext.id; 
                it[roleId] = userRole.id 
            }
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
