package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.evoleq.uuid.UUID_ZERO
import org.jetbrains.exposed.sql.*
import org.joda.time.DateTime
import org.solyton.solawi.bid.module.user.schema.MembershipStatus
import org.solyton.solawi.bid.module.user.schema.UserOrganization
import org.solyton.solawi.bid.module.user.schema.UserOrganizationHistory
import org.solyton.solawi.bid.module.user.schema.UserOrganizationHistoryEntry

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Sat Jul 18 10:06:23 CEST 2026
 *
 * Description: Add UserOrganizationHistory table and fill it with data from UserOrganization
 */
class Migration1784361983226(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1784361983226

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(UserOrganizationHistory)
        UserOrganization.join(
            UserOrganizationHistory,
            JoinType.LEFT,
            UserOrganization.id,
            UserOrganizationHistory.userOrganizationId
        ).selectAll().where{
            UserOrganizationHistory.userOrganizationId.isNull()
        }.forEach { userOrg ->
            UserOrganizationHistoryEntry.new{
                createdBy = UUID_ZERO
                userOrganizationId = userOrg[UserOrganization.id]
                status = MembershipStatus.ACTIVE
                since = DateTime(2026, 4, 1, 0, 0)
                modifiedBy = UUID_ZERO
                modifiedAt = DateTime.now()
            }
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
