package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.evoleq.uuid.UUID_ZERO
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.application.repository.createApplication
import org.solyton.solawi.bid.module.application.repository.createModule
import org.solyton.solawi.bid.module.permission.repository.*

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Wed Mar 18 11:57:11 CET 2026
 *
 * Description: Create Rights related to bank I
 */
class Migration1773831431137(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1773831431137

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val applicationContext = createRootContext("BANKING")
        val application = createApplication(
            applicationName = "BANKING",
            applicationDescription = "Application for banking",
            creator = UUID_ZERO,
            isMandatory = false,
            defaultContextId = applicationContext.id.value
        )
        val manageBankAccountsContext = applicationContext.createChild("MANAGE_BANK_ACCOUNTS")
        createModule(
            moduleName = "MANAGE_BANK_ACCOUNTS",
            moduleDescription = "Manage Bank Accounts",
            applicationId = application.id.value,
            isMandatory = true,
            creator = UUID_ZERO,
            defaultContextId = manageBankAccountsContext.id.value
        )

        val manageLegalEntitiesContext = applicationContext.createChild("MANAGE_LEGAL_ENTITIES")
        createModule(
            moduleName = "MANAGE_LEGAL_ENTITIES",
            moduleDescription = "Manage legal entities",
            applicationId = application.id.value,
            isMandatory = true,
            creator = UUID_ZERO,
            defaultContextId = manageLegalEntitiesContext.id.value
        )
        val manageSepaContext = applicationContext.createChild("MANAGE_SEPA")
        createModule(
            moduleName = "MANAGE_SEPA",
            moduleDescription = "Manage Sepa",
            applicationId = application.id.value,
            isMandatory = true,
            creator = UUID_ZERO,
            defaultContextId = manageSepaContext.id.value
        )
        val manageDatevContext = applicationContext.createChild("MANAGE_DATEV")
        createModule(
            moduleName = "MANAGE_DATEV",
            moduleDescription = "Manage DATEV",
            applicationId = application.id.value,
            isMandatory = true,
            creator = UUID_ZERO,
            defaultContextId = manageDatevContext.id.value
        )
        
        val manageBankAccounts = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "MANAGE_BANK_ACCOUNTS",
            description = "Allows to manage bank accounts"
        )
        val createBankAccounts = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "CREATE_BANK_ACCOUNTS",
            description = "Allows to create a new bank account"
        )
        val readBankAccounts = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "READ_BANK_ACCOUNTS",
            description = "Allows to read a bank account"
        )
        val updateBankAccounts = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "UPDATE_BANK_ACCOUNTS",
            description = "Allows to update a bank account"
        )
        val deleteBankAccounts = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "DELETE_BANK_ACCOUNTS",
            description = "Allows to delete a bank account"
        )
        val importBankAccounts = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "IMPORT_BANK_ACCOUNTS",
            description = "Allows to import a bank account"
        )


        val manageBankTransactions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "MANAGE_BANK_TRANSACTIONS",
            description = "Allows to manage bank transactions"
        )
        val createBankTransactions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "CREATE_BANK_TRANSACTIONS",
            description = "Allows to create a new bank transaction"
        )
        val readBankTransactions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "READ_BANK_TRANSACTIONS",
            description = "Allows to read a bank transaction"
        )
        val updateBankTransactions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "UPDATE_BANK_TRANSACTIONS",
            description = "Allows to update a bank transaction"
        )
        val deleteBankTransactions = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "DELETE_BANK_TRANSACTIONS",
            description = "Allows to delete a bank transaction"
        )

        val manageFiscalYears = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "MANAGE_FISCAL_YEARS",
            description = "Allows to manage fiscal years"
        )
        val createFiscalYears = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "CREATE_FISCAL_YEARS",
            description = "Allows to create a new fiscal year"
        )
        val readFiscalYears = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "READ_FISCAL_YEARS",
            description = "Allows to read a fiscal year"
        )
        val updateFiscalYears = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "UPDATE_FISCAL_YEARS",
            description = "Allows to update a fiscal year"
        )
        val deleteFiscalYears = createRightIfNotExists(
            creator = UUID_ZERO,
            name = "DELETE_FISCAL_YEARS",
            description = "Allows to delete a fiscal year"
        )

        // val legalEntityManager =
        createRoleIfNotExists(
            creator = UUID_ZERO,
            name = "LEGAL_ENTITY_MANAGER",
            description = "Manage legal entities"
        )

        val bankAccountManager = createRoleIfNotExists(
            creator = UUID_ZERO,
            name = "BANK_ACCOUNT_MANAGER",
            description = "Manage bank accounts"
        )

        val bankTransactionManager = createRoleIfNotExists(
            creator = UUID_ZERO,
            name = "BANK_TRANSACTION_MANAGER",
            description = "Manage bank transactions"
        )

        val legalEntity = createRoleIfNotExists(
            creator = UUID_ZERO,
            name = "LEGAL_ENTITY",
            description = "Legal entity"
        )

        (legalEntity of applicationContext).grant(
            createBankAccounts,
            readBankAccounts,
            updateBankAccounts,
            deleteBankAccounts,
            importBankAccounts,
            createFiscalYears,
            readFiscalYears,
            updateFiscalYears,
            deleteFiscalYears,
            manageFiscalYears
        )
        (bankAccountManager of applicationContext).grant(
            manageBankAccounts,
            createBankAccounts,
            readBankAccounts,
            updateBankAccounts,
            deleteBankAccounts,
            importBankAccounts,
            readFiscalYears,
        )

        (bankTransactionManager of applicationContext).grant(
            manageBankTransactions,
            createBankTransactions,
            readBankTransactions,
            updateBankTransactions,
            deleteBankTransactions,
        )

        val assignRoles = readRightByName("ASSIGN_ROLES")
        val managePermissions = readRightByName("MANAGE_PERMISSIONS")
        val permissionManager = readRoleByName("PERMISSION_MANAGER")
        (permissionManager of applicationContext).grant(
            assignRoles,
            managePermissions
        )

        val owner = readRoleByName("OWNER")
        (owner of applicationContext).grant(
            manageBankAccounts,
            manageBankTransactions,
            manageFiscalYears,
            assignRoles,
            managePermissions,
        )
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
