package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.evoleq.uuid.UUID_ZERO
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.application.schema.ApplicationEntity
import org.solyton.solawi.bid.module.application.schema.ApplicationsTable
import org.solyton.solawi.bid.module.application.service.fixApplicationContexts
import org.solyton.solawi.bid.module.banking.application.BANKING_APPLICATION_NAME
import org.solyton.solawi.bid.module.banking.permissions.CreditorIdentifiers
import org.solyton.solawi.bid.module.banking.permissions.LegalEntities
import org.solyton.solawi.bid.module.banking.permissions.Sepa
import org.solyton.solawi.bid.module.permission.repository.createRightIfNotExists
import org.solyton.solawi.bid.module.permission.repository.grant
import org.solyton.solawi.bid.module.permission.repository.of
import org.solyton.solawi.bid.module.permission.repository.readRoleByName

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Fri Aug 28 14:34:14 CEST 2026
 *
 * Description: Update Roles LEGAL_ENTITY, BANK_TRANSACTION_MANAGER
 *
 *
 */
class Migration1787920454652(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1787920454652

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val application = ApplicationEntity.find {
            ApplicationsTable.name eq BANKING_APPLICATION_NAME
        }.first()

        val context = application.defaultContext

        val legalEntity = readRoleByName("LEGAL_ENTITY")
        val createLegalEntity = createRightIfNotExists(
            LegalEntities.Rights.CREATE_LEGAL_ENTITIES,
            "",
            UUID_ZERO
        )
        val readLegalEntity = createRightIfNotExists(
            LegalEntities.Rights.READ_LEGAL_ENTITIES,
            "",
            UUID_ZERO
        )
        val updateLegalEntites = createRightIfNotExists(
            LegalEntities.Rights.UPDATE_LEGAL_ENTITIES,
            "",
            UUID_ZERO
        )
        val deleteLegalEntity = createRightIfNotExists(
            LegalEntities.Rights.DELETE_LEGAL_ENTITIES,
            "",
            UUID_ZERO
        )


        val createCreditorIdentifier = createRightIfNotExists(
            CreditorIdentifiers.Rights.CREATE_CREDITOR_IDENTIFIERS,
            "",
            UUID_ZERO
        )
        val readCreditorIdentifier = createRightIfNotExists(
            CreditorIdentifiers.Rights.READ_CREDITOR_IDENTIFIERS,
            "",
            UUID_ZERO
        )
        val updateCreditorIdentifier = createRightIfNotExists(
            CreditorIdentifiers.Rights.UPDATE_CREDITOR_IDENTIFIERS,
            "",
            UUID_ZERO
        )
        val deleteCreditorIdentifier = createRightIfNotExists(
            CreditorIdentifiers.Rights.DELETE_CREDITOR_IDENTIFIERS,
            "",
            UUID_ZERO
        )

        (legalEntity of context).grant(
            // legal entities
            createLegalEntity,
            readLegalEntity,
            updateLegalEntites,
            deleteLegalEntity,

            // creditor identifiers
            createCreditorIdentifier,
            readCreditorIdentifier,
            updateCreditorIdentifier,
            deleteCreditorIdentifier
        )

        val bankTransactionManager = readRoleByName("BANK_TRANSACTION_MANAGER")
        val createSepaMandates = createRightIfNotExists(
            Sepa.Rights.CREATE_SEPA_MANDATES,
            "",
            UUID_ZERO
        )
        val readSepaMandates = createRightIfNotExists(
            Sepa.Rights.READ_SEPA_MANDATES,
            "",
            UUID_ZERO
        )
        val updateSepaMandates = createRightIfNotExists(
            Sepa.Rights.UPDATE_SEPA_MANDATES,
            "",
            UUID_ZERO
        )
        val deleteSepaMandates = createRightIfNotExists(
            Sepa.Rights.DELETE_SEPA_MANDATES,
            "",
            UUID_ZERO
        )
        // payments
        val createSepaPayments = createRightIfNotExists(
            Sepa.Rights.CREATE_SEPA_PAYMENTS,
            "",
            UUID_ZERO
        )
        val readSepaPayments = createRightIfNotExists(
            Sepa.Rights.READ_SEPA_PAYMENTS,
            "",
            UUID_ZERO
        )
        val updateSepaPayments = createRightIfNotExists(
            Sepa.Rights.UPDATE_SEPA_PAYMENTS,
            "",
            UUID_ZERO
        )
        val deleteSepaPayments = createRightIfNotExists(
            Sepa.Rights.DELETE_SEPA_PAYMENTS,
            "",
            UUID_ZERO
        )
        // collections
        val createSepaCollections = createRightIfNotExists(
            Sepa.Rights.CREATE_SEPA_COLLECTIONS,
            "",
            UUID_ZERO
        )
        val readSepaCollections = createRightIfNotExists(
            Sepa.Rights.READ_SEPA_COLLECTIONS,
            "",
            UUID_ZERO
        )
        val updateSepaCollections = createRightIfNotExists(
            Sepa.Rights.UPDATE_SEPA_COLLECTIONS,
            "",
            UUID_ZERO
        )
        val deleteSepaCollections = createRightIfNotExists(
            Sepa.Rights.DELETE_SEPA_COLLECTIONS,
            "",
            UUID_ZERO
        )
        // messages
        val createSepaMessages = createRightIfNotExists(
            Sepa.Rights.CREATE_SEPA_MESSAGES,
            "",
            UUID_ZERO
        )
        val readSepaMessages = createRightIfNotExists(
            Sepa.Rights.READ_SEPA_MESSAGES,
            "",
            UUID_ZERO
        )
        val updateSepaMessages = createRightIfNotExists(
            Sepa.Rights.UPDATE_SEPA_MESSAGES,
            "",
            UUID_ZERO
        )
        val deleteSepaMessages = createRightIfNotExists(
            Sepa.Rights.DELETE_SEPA_MESSAGES,
            "",
            UUID_ZERO
        )

        (bankTransactionManager of context).grant(
            createSepaMandates,
            readSepaMandates,
            updateSepaMandates,
            deleteSepaMandates,

            createSepaPayments,
            readSepaPayments,
            updateSepaPayments,
            deleteSepaPayments,

            createSepaCollections,
            readSepaCollections,
            updateSepaCollections,
            deleteSepaCollections,

            createSepaMessages,
            readSepaMessages,
            updateSepaMessages,
            deleteSepaMessages,
        )

        fixApplicationContexts()
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
