package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.banking.schema.SepaMessageEntity
import org.solyton.solawi.bid.module.banking.util.toSepaMessageStatus

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Sat Aug 08 14:51:14 CEST 2026
 *
 * Description: Fix the statuses of all sepa messages
 */
class Migration1786193474640(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1786193474640

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val messages = SepaMessageEntity.all()
        messages.forEach { message ->
            val messageStatus = message.payments.map{it.status}.toSepaMessageStatus()
            if(messageStatus != null && messageStatus != message.status) {
                message.status = messageStatus
            }
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
