package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.evoleq.uuid.UUID_ZERO
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.banking.repository.createSepaPaymentTemplate
import org.solyton.solawi.bid.module.banking.schema.SepaMandateToSepaCollectionKey
import org.solyton.solawi.bid.module.banking.schema.SepaPaymentEntity
import org.solyton.solawi.bid.module.banking.schema.SepaPaymentTemplates
import org.solyton.solawi.bid.module.banking.schema.SepaPayments

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Sat Jun 27 09:03:28 CEST 2026
 *
 * Description:
 * 1. Add table [org.solyton.solawi.bid.module.banking.schema.SepaPaymentTemplates] and
 * 2. Associate a payment template with each existing payment
 */
class Migration1782543808646(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1782543808646

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(SepaPaymentTemplates)

        // Migrate existing payments without payment templates:
        // Build series of payments w.r.t. mandates and collections
        // based on the latest payment in a series of payments

        val payments = SepaPaymentEntity.find{
            SepaPayments.templateId.isNull()
        }.groupBy{
            SepaMandateToSepaCollectionKey(
                it.mandate.id.value,
                it.collection.id.value
            )
        }
        val keys = payments.keys.toList()
        keys.forEach { key ->
            val paymentsInSeries = requireNotNull(payments[key]) {"Value cannot be null by construction of the map"}
            if(paymentsInSeries.isEmpty()) return@forEach
            val latestPayment = paymentsInSeries.maxBy { payment -> payment.executionDate }
            val template = createSepaPaymentTemplate(
                UUID_ZERO,
                latestPayment.mandate,
                latestPayment.amount,
                latestPayment.collection,
            )
            paymentsInSeries.forEach { payment ->
                payment.template = template
            }
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
