package org.solyton.solawi.bid.application.data.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.evoleq.uuid.UUID_ZERO
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.application.repository.createApplication
import org.solyton.solawi.bid.module.application.repository.createModule

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Tue Aug 19 22:17:35 CEST 2025
 *
 * Description:
 * - Add Auction Application
 */
class Migration1755634655117(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1755634655117

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val auctionApplication = createApplication(
            "AUCTIONS",
            "Auctions Application",
            UUID_ZERO
        )
        createModule(
            "ORGANIZATION_MANAGEMENT",
            "Manage Organization, Members, Shares, Depots, ...",
            auctionApplication.id.value,
            UUID_ZERO
        )
        createModule(
            "AUCTION_MANAGEMENT",
            "Manage Auctions",
            auctionApplication.id.value,
            UUID_ZERO
        )
        createModule(
            "FINANCIAL_TOOLING",
            "Financial Tooling, Reporting, Forecasts, Manage Payments",
            auctionApplication.id.value,
            UUID_ZERO
        )
        createModule(
            "ORGANIZATION_TO_PROSUMER_COMMUNICATION",
            "Communicate to the Prosumers",
            auctionApplication.id.value,
            UUID_ZERO
        )
        createModule(
            "CONSENSING_TOOLS",
            "Consensing Tools helping to make better decisions in democratic communities",
            auctionApplication.id.value,
            UUID_ZERO
        )
    }

    /**
     * Downwards migration (inverse to the upward migration).
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
