name: Collect Artifacts
description: Collect all files needed to run the application
inputs:
  baseFolder:
    description: base folder for deployment
    required: true
runs:
  using: composite
  steps:
    - name: Database
      shell: bash
      run: |
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-database/docker/
        cp solawi-bid-database/e.env ${{inputs.baseFolder}}/solawi-bid-database/e.env 
        cp -r solawi-bid-database/docker/. ${{inputs.baseFolder}}/solawi-bid-database/docker/
        #  
        #mkdir -p ${{inputs.baseFolder}}/solawi-bid-database/sql/
        #cp solawi-bid-database/sql/setup.sql ${{inputs.baseFolder}}/solawi-bid-database/sql/setup.sql
    - name: Backend
      shell: bash
      run: |
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-backend/docker/ 
        cp -r solawi-bid-backend/docker/. ${{inputs.baseFolder}}/solawi-bid-backend/docker/ 
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-backend/build/resources/main/
        cp solawi-bid-backend/build/resources/main/application.conf.dist ${{inputs.baseFolder}}/solawi-bid-backend/build/resources/main/application.docker.conf
        cp solawi-bid-backend/build/resources/main/application.conf.dist ${{inputs.baseFolder}}/solawi-bid-backend/build/resources/main/application.conf
        cp solawi-bid-backend/build/resources/main/wait-for-it.sh ${{inputs.baseFolder}}/solawi-bid-backend/build/resources/main/wait-for-it.sh
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-backend/build/libs/
        cp solawi-bid-backend/build/libs/solawi-bid-backend-all.jar  ${{inputs.baseFolder}}/solawi-bid-backend/build/libs/solawi-bid-backend-all.jar
    - name: Frontend
      shell: bash
      run: |
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-frontend/docker/httpd/extra/ 
        cp solawi-bid-frontend/e.env ${{inputs.baseFolder}}/solawi-bid-frontend/e.env 
        
        cp -r solawi-bid-frontend/docker/. ${{inputs.baseFolder}}/solawi-bid-frontend/docker 
        
        cp solawi-bid-frontend/docker/httpd/httpd.conf ${{inputs.baseFolder}}/solawi-bid-frontend/docker/httpd/httpd.conf
        cp solawi-bid-frontend/docker/httpd/extra/httpd-default.conf ${{inputs.baseFolder}}/solawi-bid-frontend/docker/httpd/extra/httpd-default.conf
        cp solawi-bid-frontend/docker/httpd/extra/httpd-vhosts.conf ${{inputs.baseFolder}}/solawi-bid-frontend/docker/httpd/extra/httpd-vhosts.conf
        
       
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-frontend/build/dist/js/productionExecutable/assets/
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-frontend/build/dist/js/productionExecutable/css/
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-frontend/build/dist/js/productionExecutable/i18n/
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-frontend/build/dist/js/productionExecutable/img/
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-frontend/build/dist/js/productionExecutable/js/
        mkdir -p ${{inputs.baseFolder}}/solawi-bid-frontend/build/dist/js/productionExecutable/language/
        
        cp -r solawi-bid-frontend/build/dist/js/productionExecutable/. ${{inputs.baseFolder}}/solawi-bid-frontend/build/dist/js/productionExecutable/
    - name: Docker-Compose
      shell: bash
      run: |
        cp docker-compose.nginx.yml ${{inputs.baseFolder}}/docker-compose.yml
