name: CI Pipeline
run-name: CI Pipeline
on:
  workflow_dispatch:
  push:
      branches:
        - main
        - develop
      paths-ignore:
        - '.github/**'
  pull_request:
      branches:
        - main
        - develop
      types:
        - opened
        - reopened
        - synchronize
      paths-ignore:
        - '.github/**'
permissions:
  contents: read
  actions: read
  checks: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK, Gradle and Caches
        uses: ./.github/actions/setup

      - name: Run Detekt
        run: |
          ./gradlew detektAll

      - name: Run Backend tests
        uses: ./.github/actions/test-backend

      - name: Run Frontend tests
        uses: ./.github/actions/test-frontend
