name: Restart Server
on:
  workflow_dispatch:
  push:
    branches:
      # - main
      - devops/SMA-145/setup-workflow
    paths:
      - '.github/workflows/restart-server.yml'
  #pull_request:
  #  branches:
  #    - main
  #  paths-ignore:
  #    - '.github/**'
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  restart:
    runs-on: solyton
    steps:
      - uses: actions/checkout@v4
      - name: Restart application
        uses: ./.github/actions/restart-application
