name: Create Release from Stable Tag

on:
  workflow_call:
  workflow_dispatch:


permissions:
  contents: write  # Required to create a release

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get-tag
        run: |
          # Get the latest tag like v1.0.3.4
          LATEST_TAG=$(git tag -l "v*.*.*.*" --sort=-v:refname | head -n 1)

          # If no tag is found, exit
          if [[ -z "$LATEST_TAG" ]]; then
            echo "No previous tag found!"
            exit 1
          fi

          # Extract the first three digits (ignore the last digit)
          BASE_VERSION=v$(echo $LATEST_TAG | sed -E 's/v([0-9]+\.[0-9]+\.[0-9]+)\.[0-9]+/\1/')
          
          # Export the base version to use in the release step
          echo "BASE_VERSION=$BASE_VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release from Base Version
        env:
          PUSH_TAGS_PAT: ${{ secrets.PUSH_TAGS_PAT }}  # Use the custom token here
        run: |
          # Set up release information
          RELEASE_NAME="Release $BASE_VERSION"
          BODY="This is the stable release of $BASE_VERSION."
          
          # Create the GitHub Release from the base version (without the last digit)
          curl -X POST \
            -H "Authorization: token $PUSH_TAGS_PAT" \
            -d '{
                  "tag_name": "'"$BASE_VERSION"'",
                  "name": "'"$RELEASE_NAME"'",
                  "body": "'"$BODY"'",
                  "draft": false,
                  "prerelease": false,
                  "latest": true
                }' \
            https://api.github.com/repos/doctor-smith/solawi-bid/releases
